package com.raos.fx.controls.models.occurance;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Collection;
import java.util.Collections;
import java.util.Map;
import java.util.Objects;

/**
 * The class which represents a Daily Occurance
 * @author Raos
 *
 */
public final class DailyOccurance extends Occurance {
	private LocalDate startDay, endDay;
	private Collection<LocalDate> excludes;

	/**
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @return an instance of the class DailyOccurance
	 */
	public static DailyOccurance dailyOccurance(LocalTime startTime, LocalTime endTime) {
		return dailyOccurance(startTime, endTime, LocalDate.now(), LocalDate.MAX);
	}

	/**
	 * 
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @param startDay - the start day
	 * @param endDay - the end day
	 * @return an instance of the class DailyOccurance
	 */
	public static DailyOccurance dailyOccurance(LocalTime startTime, LocalTime endTime, LocalDate startDay,
			LocalDate endDay) {
		return dailyOccurance(startTime, endTime, startDay, endDay, Collections.emptyList());
	}

	/**
	 * 
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @param startDay - the start day
	 * @param endDay - the end day
	 * @param excludes - the days excluded
	 * @return an instance of the class DailyOccurance
	 */
	public static DailyOccurance dailyOccurance(LocalTime startTime, LocalTime endTime, LocalDate startDay,
			LocalDate endDay, Collection<LocalDate> excludes) {
		DailyOccurance occurance = new DailyOccurance();
		occurance.setStartTime(startTime);
		occurance.setEndTime(endTime);
		occurance.setStartDay(startDay);
		occurance.setEndDay(endDay);
		occurance.setExcludes(excludes);
		return occurance;
	}

	/**
	 * @return startDay
	 */
	public final LocalDate getStartDay() {
		return startDay;
	}

	/**
	 * @param startDay - to be set
	 */
	public final void setStartDay(LocalDate startDay) {
		this.startDay = startDay;
	}

	/**
	 * @return endDay
	 */
	public final LocalDate getEndDay() {
		return endDay;
	}

	/**
	 * @param endDay - to be set
	 */
	public final void setEndDay(LocalDate endDay) {
		this.endDay = endDay;
	}

	/**
	 * @return excludes
	 */
	public final Collection<LocalDate> getExcludes() {
		return excludes;
	}

	/**
	 * @param excludes - to be set
	 */
	public final void setExcludes(Collection<LocalDate> excludes) {
		this.excludes = excludes;
	}

	@Override
	public int hashCode() {
		// auto generated by eclipse
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + Objects.hash(endDay, excludes, startDay);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		// auto generated by eclipse
		if (this == obj) {
			return true;
		}
		if (!super.equals(obj)) {
			return false;
		}
		if (!(obj instanceof DailyOccurance)) {
			return false;
		}
		DailyOccurance other = (DailyOccurance) obj;
		return Objects.equals(endDay, other.endDay) && Objects.equals(excludes, other.excludes)
				&& Objects.equals(startDay, other.startDay);
	}

	@Override
	public Often getOften() {
		return Often.DAILY;
	}

	@Override
	public boolean isAvailable(LocalDate date) {
		return !excludes.contains(date) && !startDay.isAfter(date) && !endDay.isBefore(date);
	}
	
	@Override
	public Map<String, Object> transform(Map<String, Object> t) {
		Map<String, Object> map = super.transform(t);
		map.put("Start Date", startDay);
		map.put("End Date", endDay);
		map.put("Excludes", excludes);
		return map;
	}
}
