package com.raos.fx.controls.models.occurance;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Collection;
import java.util.Collections;
import java.util.Map;
import java.util.Objects;

import com.raos.fx.controls.models.Transformable;

/**
 * A class representing a monthly occurance of a task
 * @author Raos
 *
 */
public final class MonthlyOccurance extends Occurance {
	private LocalDate startDay, endDay;
	private Collection<LocalDate> excludes;
	private Collection<Integer> days;

	private MonthlyOccurance() {
	}

	/**
	 * 
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @param days - the days
	 * @return an instance of the MonthlyOccurance class
	 */
	public static MonthlyOccurance monthlyOccurance(LocalTime startTime, LocalTime endTime, Collection<Integer> days) {
		return monthlyOccurance(startTime, endTime, days, LocalDate.now(), LocalDate.MAX);
	}

	/**
	 * 
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @param days - the days
	 * @param start - the start date
	 * @param end - the end date
	 * @return an instance of the MonthlyOccurance class
	 */
	public static MonthlyOccurance monthlyOccurance(LocalTime startTime, LocalTime endTime, Collection<Integer> days,
			LocalDate start, LocalDate end) {
		return monthlyOccurance(startTime, endTime, days, start, end, Collections.emptyList(), LocalTime.MIN);
	}

	/**
	 * 
	 * @param startTime - the start time
	 * @param endTime - the end time
	 * @param days - the days
	 * @param start - the start date
	 * @param end - the end date
	 * @param excludes - the excluded days
	 * @param reminderTime - the reminder time
	 * @return an instance of the MonthlyOccurance class
	 */
	public static MonthlyOccurance monthlyOccurance(LocalTime startTime, LocalTime endTime, Collection<Integer> days,
			LocalDate start, LocalDate end, Collection<LocalDate> excludes, LocalTime reminderTime) {
		MonthlyOccurance occurance = new MonthlyOccurance();
		occurance.setStartTime(startTime);
		occurance.setEndTime(endTime);
		occurance.setStartDay(start);
		occurance.setEndDay(end);
		occurance.setDays(days);
		occurance.setExcludes(excludes);
		occurance.setReminderTime(reminderTime);
		return occurance;
	}

	/**
	 * @return startDay
	 */
	public final LocalDate getStartDay() {
		return startDay;
	}

	/**
	 * @param startDay - to be set
	 */
	public final void setStartDay(LocalDate startDay) {
		this.startDay = startDay;
	}

	/**
	 * @return endDay
	 */
	public final LocalDate getEndDay() {
		return endDay;
	}

	/**
	 * @param endDay - to be set
	 */
	public final void setEndDay(LocalDate endDay) {
		this.endDay = endDay;
	}

	/**
	 * @return excludes
	 */
	public final Collection<LocalDate> getExcludes() {
		return excludes;
	}

	/**
	 * @param excludes - to be set
	 */
	public final void setExcludes(Collection<LocalDate> excludes) {
		this.excludes = excludes;
	}

	/**
	 * @return days
	 */
	public final Collection<Integer> getDays() {
		return days;
	}

	/**
	 * @param days - to be set
	 */
	public final void setDays(Collection<Integer> days) {
		this.days = days;
	}

	@Override
	public int hashCode() {
		// auto generated by eclipse
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + Objects.hash(days, endDay, excludes, startDay);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		// auto generated by eclipse
		if (this == obj) {
			return true;
		}
		if (!super.equals(obj)) {
			return false;
		}
		if (!(obj instanceof MonthlyOccurance)) {
			return false;
		}
		MonthlyOccurance other = (MonthlyOccurance) obj;
		return Objects.equals(days, other.days) && Objects.equals(endDay, other.endDay)
				&& Objects.equals(excludes, other.excludes) && Objects.equals(startDay, other.startDay);
	}

	@Override
	public Often getOften() {
		return Often.MONTHLY;
	}

	@Override
	public boolean isAvailable(LocalDate date) {
		return !excludes.contains(date) && !startDay.isAfter(date) && !endDay.isBefore(date)
				&& days.contains(date.getDayOfMonth());
	}
	
	@Override
	public Map<String, Object> transformTo(Map<String, Object> t) {
		Map<String, Object> map = super.transformTo(t);
		map.put("Start Date", startDay);
		map.put("End Date", endDay);
		map.put("Excludes", excludes);
		map.put("Days", days);
		return map;
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public Transformable<Map<String, Object>> transformFrom(Map<String, Object> t) {
		startDay = (LocalDate) t.get("Start Date");
		endDay = (LocalDate) t.get("End Date");
		excludes = (Collection<LocalDate>) t.get("Excludes");
		days = (Collection<Integer>) t.get("Days");
		return super.transformFrom(t);
	}

}
