package com.raos.fx.controls.models.occurance;

import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.FormatStyle;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import com.raos.fx.controls.models.Transformable;

import javafx.util.converter.LocalTimeStringConverter;

/**
 * The Occurance of a Task which includes time duration
 * @author Raos
 */
public abstract class Occurance implements Transformable<Map<String, Object>> {
	/**
	 * MAX and MIN of Time represented in the Scheduler
	 */
	public static final LocalTime MIN = LocalTime.MIN, MAX = LocalTime.MAX.truncatedTo(ChronoUnit.MINUTES);
	private static final LocalTimeStringConverter converter = new LocalTimeStringConverter(FormatStyle.SHORT,
			Locale.CANADA);
	private LocalTime startTime, endTime;
	private LocalTime reminderTime;

	/**
	 * @return The start time of the occurance
	 */
	public final LocalTime getStartTime() {
		return startTime;
	}

	/**
	 * @param startTime - to be set
	 */
	public final void setStartTime(LocalTime startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return The end time of the occurance
	 */
	public final LocalTime getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime - to be set
	 */
	public final void setEndTime(LocalTime endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return How often the occurance is
	 */
	public abstract Often getOften();

	/**
	 * The Enum of how often an occurance is
	 * @author Raos
	 */
	public static enum Often {
		ONCE, DAILY, WEEKLY, MONTHLY, YEARLY	
	}
	
	/**
	 * @return the time duration
	 */
	public final Duration getTimeDuration() {
		return Duration.between(startTime, endTime);
	}

	@Override
	public int hashCode() {
		// autogenerated by eclipse
		return Objects.hash(endTime, startTime);
	}

	@Override
	public boolean equals(Object obj) {
		// autogenerated by eclipse
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Occurance)) {
			return false;
		}
		Occurance other = (Occurance) obj;
		return Objects.equals(endTime, other.endTime) && Objects.equals(startTime, other.startTime);
	}

	/**
	 * Checks if an this intersects with another occurance
	 * @param other - the other occurance
	 * @return whether it intersects or not
	 */
	public final boolean intersectsWith(Occurance other) {
		if (other == null) {
			throw new NullPointerException("other cannot be null");
		}
		// check if it equal to the other or it starts before the end and ends after the begining
		if (this.equals(other) || this == other) {
			return true;
		}
		return (this.startTime.isBefore(other.endTime)) && (other.startTime.isAfter(this.endTime));
	}

	/**
	 * @return if it is a fullday
	 */
	public final boolean isFullDay() {
		return startTime.equals(MIN) && endTime.equals(MAX);
	}

	/**
	 * @return The Reminder Time
	 */
	public final LocalTime getReminderTime() {
		return reminderTime;
	}

	/**
	 * @param reminderTime - to be set
	 */
	public final void setReminderTime(LocalTime reminderTime) {
		this.reminderTime = reminderTime;
	}

	/**
	 * Checks if it is available on this day
	 * @param date - the date it is available on
	 * @return
	 */
	public abstract boolean isAvailable(LocalDate date);
	
	@Override
	public Map<String, Object> transform(Map<String, Object> t) {
		Map<String, Object> map = Optional.ofNullable(t).orElseGet(HashMap::new);
		map.put("Name", "Occurance");
		map.put("Start Time", converter.toString(startTime));
		map.put("End Time", converter.toString(endTime));
		map.put("Reminder Time", converter.toString(reminderTime));
		return map;
	}
}


